apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNRjV0dCtMSmNlWHZIZjJYUU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05Nak14TVRJMU1EZ3pOalF3V2hjTk16TXhNVEkwTURnegpOalF3V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdjZZamNkaWFvWDdpVnB3MlkzRk5DSGQzaXo1TUd0ZnNqQTJia0NSaTdvY2MKN3pwNEJ4ZEhiSlluUmh0YzBHa1ViSWFNN2d2ZFJYcUFjRG1talBNampIQ3A3eTZseVJNbW9QaUp6ekRTQmpxNQpIL1J5NkFQRE82L1l5VWpsaEVVYXljV1hycU5CZ2RrVERMU3dESS9QUjVrNkpIM0JSWnM1b3NwRFZqRW45WlV0Cnd6cGU4T1JFUUp5SWVwRUhHdE5CNk1ac3VoRVIyWkoySDdSbDJLVU1iaEhjQUVyZzVEQ3UxQWYzQTh3MU90cHAKc3V5L0Zwd1Y0ZDBlS3NJUVRYeGZ2R0VlRW1lYnRrWHBkQlE2R1ROVXdmTTVhZ2I4MmM3dU85aWIvUDNoek1WSQoyQ1BBWEcvUjVvcTRsVkQxTUw2UjIyRE5JL0JTWHM5UlFzczN0MGp0dVFJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFoSDFEQWQ2TmNZRUJHOGMKY3dCQzc2MDljeDR3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtjMnV6bWFEbFhtT0tjd3FYUSt4bGYyWFZmbgp6anNXb2J2VVk4OGZMdmZKTzhZZVZiWjA0ZjVWT0tlNjhnM0hEcS9HSkdyMUdLTlliZHJrVTFnd09INHYvVnpNCkx3cU1iVTZWN0ZPSGRaTUJzb2ZmWlIzZnM3bjlmd3ZqbWcvZHpLV3ZmeDEwU0trK2VpQk01dnZVci9qeFRacXUKL2k4U1R5bk5STEpuVUxmb3NHcmMxMHlBa1ZDSHIrMlBYVS9mTnRhTWZlaURwREx4VjJYZE92UENZcGowdnUvRApYUEZPbGhSa2ZiQmlmbXppbTdOVDl2TTFXYXdTSzdjMFJ6ZnE4WDZEbXdDbEc5S2U1cEhNZlo5dTNadFpJbm1TCjIyeVdRcloyc0NtVFVtMTNpOEFsbkt4TTFqRktKeUxMQ0hXNFNZeTc1MEVFVWpVTnBTNnZPUi81ZzBVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.pinapathrunisaikiran.co.in
    tls-server-name: api.internal.pinapathrunisaikiran.co.in
  name: pinapathrunisaikiran.co.in
contexts:
- context:
    cluster: pinapathrunisaikiran.co.in
    namespace: development
    user: chandra
  name: chandra-context
current-context: chandra-context
kind: Config
users:
- name: chandra
  user:
    client-certificate: /root/chandra.crt
    client-key: /root/chandra.key