kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: all-users-default-role
rules:
- apiGroups: ["", "apps" , "networking.k8s.io"] 
  resources: ["pods", "secrets" , "services" , "nodes" , "deployments", "replicasets", "ingresses"]
  verbs: ["get", "update", "list", "create", "delete"]